language: python
services: docker
env:
  global:
    - ROLE_NAME: vsftpd
before_install:
  - sudo apt-get -qq update
install:
  - python3 -m pip install ansible
  - python3 -m pip install molecule[docker,lint]
before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME
script:
  - molecule --version
  - ansible --version
  - ansible-lint --version
  - yamllint --version
  - molecule test
notifications:
  email: false
  slack:
    secure: XRGQBJhuzz5b1jQ6vNTV1klNbSG5eMsDzdO1vpFkMHtUzX9ktec85zQ6tos+IGDPZJDVcH8JEy0bqNR5SmImJ9R4HF4EVlTt9mV1hq2n/sjVOmKDcpW0GODo1sUsKNFf99CVf5pKmkmPpCUoqkm87HRCJ6vR6w0q5GthMXnd9FlXKM4ras8tATB25lnY/VVyftQQejue1uJNKCySLIfGp8EIfOz0XklyCqQOfPDrS/fHCBME1JlyWk5dy1b3EDuAtOE0Qy5oEEN3oN+SYi2HdY7euQJLv4e60pkoUKYdKaR/1WvW/Y8/Ej6kt/SHKn3ZJ5AfkjMzb5bL1M75SB+hWBfDG4vWgDpsyYs+RKD2oHSFJx9nsspcAThj0wEE2xoaPX9J7ZZW3gFDpHNpTgMV6hfMIBm7RzcEM9Uzpwm6RM2jP3WBs2b3KUUlP+GsaLBLbwkT47sh68Xyg0k5NtC8BpK1IFC0m0Dq/jReL7c8K+wDeHypOjd//y/31HfLQ1biIazD0Xf77VzjkOVrCHutRrWGzEjalHcreVgDj+zRxjY2O4n3Ti4zQnQ5B2aJk20pTz1Un/BSDv/BLRfUgNEt+dmJFD7lie2E+Hu6d3g+vmI4Mf4x71KA6BpncnE8BLtj5C12pPoryLuHGZTz2qrJg3YDWBCl4whE/GQvRBROTcI=
